#云编译公用核心
name: BuildFirmware

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner On ubuntu-latest or self-hosted'
        required: true
        type: string
      config:
        required: true
        type: string
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      source:
        required: true
        type: string
      config_only:
        required: true
        type: boolean
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  WRT_CONFIG: ${{inputs.config}}
  WRT_REPO: ${{inputs.repo}}
  WRT_BRANCH: ${{inputs.branch}}
  WRT_SOURCE: ${{inputs.source}}
  CONFIG_ONLY: ${{inputs.config_only}}

jobs:
  core:
    name: ${{inputs.config}}
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq full-upgrade
          sudo -E apt-get -yqq autoremove --purge
          sudo -E apt-get -yqq autoclean
          sudo -E apt-get -yqq clean
          sudo -E apt-get -yqq install dos2unix python3-netifaces libfuse-dev

          sudo -E apt-get -yqq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Clone & Update Code
        run: |
          if [ -d $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}} ]; then
            echo "Directory exists"
            cd $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}
            git pull
          else
            echo "Directory does not exist"
            git clone --depth=1 --branch $WRT_BRANCH $WRT_REPO $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}
          fi

          sudo chown $USER:$USER $GITHUB_WORKSPACE
          sudo chown $USER:$USER $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}

      - name: Check Caches
        id: check-cache
        if: env.CONFIG_ONLY != 'true' && inputs.runner != 'self-hosted'
        uses: actions/cache@main
        with:
          key: ${{inputs.source}}-${{inputs.branch}}-${{env.WRT_HASH}}-${{env.WRT_CONFIG}}
          restore-keys: ${{inputs.source}}-${{inputs.branch}}
          path: |
            $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}/.ccache
            $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}/staging_dir/host*
            $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}/staging_dir/tool*

      - name: Update Caches
        if: env.CONFIG_ONLY != 'true' && inputs.runner != 'self-hosted'
        run: |
          path="$GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}/staging_dir"
          if [ -d "$path" ]; then
            find "$path" -type d -name "stamp" -not -path "*target*" | while read -r DIR; do
              find "$DIR" -type f -exec touch {} +
            done

            mkdir -p "$path/tmp" && echo "1" > "$path/tmp/.build"

            echo "toolchain skiped done!"
          else
            echo "caches missed!"
          fi

          if ${{steps.check-cache.outputs.cache-hit != 'true'}}; then
            KEY="${{inputs.source}}-${{inputs.branch}}"
            CACHE_LIST=$(gh cache list --key "$KEY" | cut -f 1)
            for CACHE_KEY in $CACHE_LIST; do
              gh cache delete $CACHE_KEY
            done

            echo "caches cleanup done!"
          fi

      - name: Update Feeds
        run: |
          cd $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom Settings
        run: |
          cd $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}

          cat $GITHUB_WORKSPACE/Config/$WRT_CONFIG.txt $GITHUB_WORKSPACE/Config/DIFF.txt >> .config          

          $GITHUB_WORKSPACE/Scripts/Settings.sh

          make defconfig -j$(nproc) && make clean -j$(nproc)

      - name: Download Packages
        if: env.CONFIG_ONLY != 'true'
        run: |
          cd $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}
          cat -n .config

          make download -j$(nproc)

      - name: Compile Firmware
        if: env.CONFIG_ONLY != 'true'
        run: |
          cd $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}}

          make -j$(nproc) || make -j1 V=s

      - name: Package Firmware
        run: |
          cd $GITHUB_WORKSPACE/${{inputs.source}}/${{inputs.branch}} && mkdir upload

          cp -f ./.config ./upload/Config.txt

          if [[ $CONFIG_ONLY != 'true' ]]; then
            find ./bin/targets/ -iregex ".*\(buildinfo\|json\|sha256sums\|packages\)$" -exec rm -rf {} +
            
            WRT_TARGET=$(grep -m 1 -oP '^CONFIG_TARGET_\K[\w]+(?=\=y)' $GITHUB_WORKSPACE/Config/$WRT_CONFIG.txt)
            for FILE in $(find ./bin/targets/ -type f -iname "*$WRT_TARGET*") ; do
              EXT=$(basename $FILE | cut -d '.' -f 2-)
              NAME=$(basename $FILE | cut -d '.' -f 1 | grep -io "\($WRT_TARGET\).*")
              NEW_FILE="$NAME"."$EXT"
              mv -f $FILE ./upload/$NEW_FILE
            done

            find ./bin/targets/ -type f -exec mv -f {} ./upload/ \;

            make clean -j$(nproc)
          fi

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{inputs.source}}/${{inputs.branch}}@${{env.WRT_GIT_HASH}}:${{env.WRT_CONFIG}}
          files: ./wrt/upload/*.*
          body: |
            源码：${{inputs.source}}
            分支：${{inputs.branch}}
            提交：${{env.WRT_GIT_HASH}}
